// Margoria Assets - Archivo modificable con todos los assets
window.ASSETS = {
  fonts: [
    { family: "capo1880", file: "fonts/Capo1880.woff2" },
    { family: "pfeffermediaeval", file: "fonts/PfefferMediaeval.woff2" },
    { family: "codexmanesse", file: "fonts/codex_manesse.woff2" },
    { family: "cissanthemos", file: "fonts/Cissanthemos.woff2" },
    { family: "hicopus", file: "fonts/HocOpus-Regular.woff2" },
    { family: "icigist", file: "fonts/IciGist-Regular.woff2" },
    { family: "indiebusillis", file: "fonts/Indiebusillis.woff2" },
    { family: "litteraeignotae", file: "fonts/LitteraeIgnotae.woff2" },
    { family: "malatemporacurrunt", file: "fonts/Malatemporacurrunt-Regular.woff2" },
    { family: "pfeffersimpelgotisch", file: "fonts/PfefferSimpelgotisch.woff2" },
    { family: "quariteregnumdei", file: "fonts/QuaeriteRegnumDei.woff2" },
    { family: "sprangalongobarda", file: "fonts/SprangaLongobarda-Regular.woff2" },
    { family: "vulnus", file: "fonts/Vulnus-Regular.woff2" },
    { family: "zifferaveneta", file: "fonts/Zifferaveneta-Regular.woff2" },
    { family: "andiamoabruciarglilacasa", file: "fonts/Andiamoabruciarglilacasa-Reg.woff2" },
    { family: "capoecclesia", file: "fonts/CapoEcclesia-Regular.woff2" },
    { family: "capolinea", file: "fonts/Capolinea-Regular.woff2" }
  ],
  backgrounds: [
    { name: "Horae ad usum Trecensem (1415)", src: "images/background/horae_ad_usum_trecensem_1415-20.png" },
    { name: "Chansonnier Cordiforme", src: "images/background/chansonnier_cordiforme_de_montchenu.png" },
    { name: "Liège – Book of Hours", src: "images/background/liège_book_of_hours_ms_w16.png" },
    { name: "Belgium 1480, MS M.493", src: "images/background/book_of_hours_belgium_1480_ms_m493.jpg" },
    { name: "Horae ad usum Trecensem II", src: "images/background/horae_ad_usum_trecensem_1415-20_2.jpg" },
    { name: "Les voeux du paon", src: "images/background/les_voeux_du_paon_1350.jpg" },
    { name: "Plain parchment", src: "images/background/parchment.jpg" }
  ],
  caps: [
    { id: "cap_a", src: "images/caps/a.png" },
    { id: "cap_b", src: "images/caps/b.png" },
    { id: "cap_c", src: "images/caps/c.png" },
    { id: "cap_d", src: "images/caps/d.png" },
    { id: "cap_e", src: "images/caps/e.png" },
    { id: "cap_f_hist", src: "images/caps/f_scriptores_historiae_augustae.png" },
    { id: "cap_g", src: "images/caps/g.png" },
    { id: "cap_h", src: "images/caps/h.png" },
    { id: "cap_i_hist", src: "images/caps/i_scriptores_historiae_augustae.png" },
    { id: "cap_j", src: "images/caps/j.png" },
    { id: "cap_k", src: "images/caps/k.png" },
    { id: "cap_l", src: "images/caps/l.png" },
    { id: "cap_m", src: "images/caps/m.png" },
    { id: "cap_n", src: "images/caps/n.png" },
    { id: "cap_o", src: "images/caps/o.png" },
    { id: "cap_p_hist", src: "images/caps/p_scriptores_historiae_augustae.png" },
    { id: "cap_r", src: "images/caps/r.png" },
    { id: "cap_s", src: "images/caps/s.png" },
    { id: "cap_t_hist", src: "images/caps/t_scriptores_historiae_augustae.png" },
    { id: "cap_u", src: "images/caps/u.png" },
    { id: "cap_w", src: "images/caps/w.png" },
    { id: "cap_y", src: "images/caps/y.png" },
    { id: "cap_z", src: "images/caps/z.png" }
  ],
  borders: [
    { id: "border_", src: "images/border/french_bestiary_amphisbaena_m.png" },
    { id: "border_", src: "images/border/liège_book_of_hours_ms_w16_2.png" },
    { id: "border_", src: "images/border/liège_book_of_hours_ms_w16_3.png" },
    { id: "border_", src: "images/border/liège_book_of_hours_ms_w16_4.png" },
    { id: "border_", src: "images/border/liège_book_of_hours_ms_w16_5.png" },
    { id: "border_", src: "images/border/liège_book_of_hours_ms_w16_6.png" },
    { id: "border_", src: "images/border/liège_book_of_hours_ms_w16_7.png" },
    { id: "border_", src: "images/border/lutterell_fighting_dragons_m.png" },
    { id: "border_", src: "images/border/lutterell_goatbird_m.png" },
    { id: "border_", src: "images/border/luttrell_bird_dividerpng_m.png" },
    { id: "border_", src: "images/border/Luttrell_birds_m.png" },
    { id: "border_", src: "images/border/luttrell_demondragingdragon_m.png" },
    { id: "border_", src: "images/border/luttrell_guy_divider_m.png" },
    { id: "border_", src: "images/border/luttrell_hydra_n.png" },
    { id: "border_", src: "images/border/luttrell_rat_eating_fish_m.png" },
    { id: "border_", src: "images/border/n.png" },
    { id: "border_", src: "images/border/Royal_MS_12C_XIX_basilisk_nn.png" },
  ],
  marginalias: [
    { id: "marg_", src: "images/marginalias/aberdeen_bestiary_amphisbaena_m.png" },
    { id: "marg_", src: "images/marginalias/aberdeen_bestiary_cat1_n.png" },
    { id: "marg_", src: "images/marginalias/aberdeen_bestiary_cat2_n.png" },
    { id: "marg_", src: "images/marginalias/aberdeen_bestiary_cat3_n.png" },
    { id: "marg_", src: "images/marginalias/anabasis_1501_screamingsnail_n.png" },
    { id: "marg_", src: "images/marginalias/apple-touch-icon.png" },
    { id: "marg_", src: "images/marginalias/babyforge.png" },
    { id: "marg_", src: "images/marginalias/beastiary_1.png" },
    { id: "marg_", src: "images/marginalias/Bestiaire_of_Pierre_de_Beauvais_basilisk_n.png" },
    { id: "marg_", src: "images/marginalias/Bestiaire_of_Pierre_de_Beauvais_basilisk2_n.png" },
    { id: "marg_", src: "images/marginalias/bestiary_england_1200_dragonandelephant_n.png" },
    { id: "marg_", src: "images/marginalias/bestiary_of_ann_walsh_cat_n.png" },
    { id: "marg_", src: "images/marginalias/Bestiary_Royal_MS_12_C_XIX_1200-1210_hydra.png" },
    { id: "marg_", src: "images/marginalias/Bible_France_1270-1290_Lilguy_n.png" },
    { id: "marg_", src: "images/marginalias/Biblia_Porta-france_13th_century.png" },
    { id: "marg_", src: "images/marginalias/book of hours_Savoie_15thc_donkeyguy_n.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_England_1320-1330_n.png" },
    { id: "marg_", src: "images/marginalias/book_of_hours_Flanders_14th_century_n.png" },
    { id: "marg_", src: "images/marginalias/book_of_hours_France_15thc_catlute_n.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_France_Paris_1420-1425_cat.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_France_Paris_1420-1425_hedgehog.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_France_Paris_1420-1425_mouser.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_France_Paris_1480-1500_catviolin.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_France_Rouen_1500_birdcreature.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_Lyon_1505-1510_cat_n.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_of_Leonor_de_la_Vega_Birdlady_r.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_of_Leonor_de_la_Vega_creature_n.png" },
    { id: "marg_", src: "images/marginalias/Book_of_Hours_of_Leonor_de_la_Vega_creature2_n.png" },
    { id: "marg_", src: "images/marginalias/Breviary_of_Renaud_1302-1303_rabbit1.png" },
    { id: "marg_", src: "images/marginalias/Breviary_of_Renaud_1302-1303_rabbit2.png" },
    { id: "marg_", src: "images/marginalias/Breviary_of_Renaud_1302-1305.png" },
    { id: "marg_", src: "images/marginalias/bruges_book_of_hours_1500_chickensnail_n.png" },
    { id: "marg_", src: "images/marginalias/bruges_book_of_hours_1510-1525_snailberries_n.png" },
    { id: "marg_", src: "images/marginalias/caelum_1.png" },
    { id: "marg_", src: "images/marginalias/castle_1.png" },
    { id: "marg_", src: "images/marginalias/castle_2.png" },
    { id: "marg_", src: "images/marginalias/Chansonnier_de_Jean_de_Montchenu_1475_cat.png" },
    { id: "marg_", src: "images/marginalias/Chronique_ sire_Jehan_Froissart_folio153v2_n.png" },
    { id: "marg_", src: "images/marginalias/Chroniques_sire_Jehan_Froissart_folio6r.png" },
    { id: "marg_", src: "images/marginalias/Chroniques_sire_Jehan_Froissart_folio58v2_n.png" },
    { id: "marg_", src: "images/marginalias/Chroniques_sire_Jehan_Froissart_folio79r2_n.png" },
    { id: "marg_", src: "images/marginalias/Chroniques_sire_Jehan_Froissart_folio176r3_n.png" },
    { id: "marg_", src: "images/marginalias/Consolation_of_Philosophy_1300-1305.png" },
    { id: "marg_", src: "images/marginalias/cosplay.png" },
    { id: "marg_", src: "images/marginalias/De_Natura_animalium_1270-1275_harpy.png" },
    { id: "marg_", src: "images/marginalias/demonwriter.png" },
    { id: "marg_", src: "images/marginalias/Der_Naturen_Bloeme_1287_hippopotamus.png" },
    { id: "marg_", src: "images/marginalias/Der_Naturen_Bloeme_1300-1325_Caan.png" },
    { id: "marg_", src: "images/marginalias/Der_Naturen_Bloeme_1300-1325_giraff.png" },
    { id: "marg_", src: "images/marginalias/Der_Naturen_Bloeme_1350_fishguy.png" },
    { id: "marg_", src: "images/marginalias/Der_Naturen_Bloeme_1350_Harpy.png" },
    { id: "marg_", src: "images/marginalias/dreamlogo.png" },
    { id: "marg_", src: "images/marginalias/embroidery.png" },
    { id: "marg_", src: "images/marginalias/everyday.png" },
    { id: "marg_", src: "images/marginalias/French_bestiary_basilisk_nn.png" },
    { id: "marg_", src: "images/marginalias/french_book_of_hours__1460_chickenrider_n.png" },
    { id: "marg_", src: "images/marginalias/french_book_of_hours_14birdreader_n.png" },
    { id: "marg_", src: "images/marginalias/french_book_of_hours_1440_goatsnail_n.png" },
    { id: "marg_", src: "images/marginalias/french_book_of_hours_after1500_cat_n.png" },
    { id: "marg_", src: "images/marginalias/Froissart_folio176r_2_n.png" },
    { id: "marg_", src: "images/marginalias/Froissart_folio176r_harpy_and_guy_n.png" },
    { id: "marg_", src: "images/marginalias/Greek_Physiologus_16t-c_frod.png" },
    { id: "marg_", src: "images/marginalias/harley_ms_3244_amphisbaena_nn.png" },
    { id: "marg_", src: "images/marginalias/heures_de_jacques_de_rambures_1460_snailwoman.png" },
    { id: "marg_", src: "images/marginalias/Heures_de_Jacques_de_Rambures_1460_snailwoman_n.png" },
    { id: "marg_", src: "images/marginalias/Heures_de_Nôtre_Dame_1470_goatsnail_n.png" },
    { id: "marg_", src: "images/marginalias/Horae_ad_usum_Rotomagensem_Date_dedition _1401-1500_m.png" },
    { id: "marg_", src: "images/marginalias/Hours_of_Joanna_the_Mad_cat2_n.png" },
    { id: "marg_", src: "images/marginalias/Hours_of_Joanna_the_Mad_deersnail_n.png" },
    { id: "marg_", src: "images/marginalias/Hours_of_Joanna_the_Mad_deersnail2_n.png" },
    { id: "marg_", src: "images/marginalias/Hugh_of_Fouilloy_Bestiary_1270_harpy.png" },
    { id: "marg_", src: "images/marginalias/humanlike_1.png" },
    { id: "marg_", src: "images/marginalias/institutes_of_justinian_Frod_n.png" },
    { id: "marg_", src: "images/marginalias/institutes_of_justinian_snail_n.png" },
    { id: "marg_", src: "images/marginalias/its_ok.png" },
    { id: "marg_", src: "images/marginalias/Jean_Mansel_1454_cat_n.png" },
    { id: "marg_", src: "images/marginalias/jewellery.png" },
    { id: "marg_", src: "images/marginalias/knitting.png" },
    { id: "marg_", src: "images/marginalias/La_Dance_aux_aveigles_1466_snail_rider_n.png" },
    { id: "marg_", src: "images/marginalias/Le_Livre_des_hystoires_du_Mirouer_du_monde_snaildragon_n.png" },
    { id: "marg_", src: "images/marginalias/Le_Livre_des_hystoires_du_Mirouer_du_monde_snailwoman_n.png" },
    { id: "marg_", src: "images/marginalias/le_roman_de_fauvel_1320.png" },
    { id: "marg_", src: "images/marginalias/Liber_de_natura_rerum_cat_n.png" },
    { id: "marg_", src: "images/marginalias/lildemon.png" },
    { id: "marg_", src: "images/marginalias/Livre_de_la_Vigne_nostre_Seigneur_France_1450-1470_m2.png" },
    { id: "marg_", src: "images/marginalias/Livre_de_la_Vigne_nostre_Seigneur_France_c_1450-1470_1m.png" },
    { id: "marg_", src: "images/marginalias/Livre_de_la_Vigne_nostre_Seigneur_France_c-1450-1470_n.png" },
    { id: "marg_", src: "images/marginalias/Livre_de_la_Vigne_nostre_Seigneur_France_c-1450-1470n.png" },
    { id: "marg_", src: "images/marginalias/lutterell_cat.png" },
    { id: "marg_", src: "images/marginalias/lutterell_cat_n.png" },
    { id: "marg_", src: "images/marginalias/lutterell_cat2_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell.f.48r_sassy_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell.f.50r_amphisbaena_nn.png" },
    { id: "marg_", src: "images/marginalias/luttrell_alligator_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_amphisbaena_2_nn.png" },
    { id: "marg_", src: "images/marginalias/luttrell_amphisbaena_bird_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_bat_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_batcreature.png" },
    { id: "marg_", src: "images/marginalias/luttrell_birdcreature_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_birdguy_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_birdsnail_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_birdsnail2_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_cat_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_cats_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_chemist_n.png" },
    { id: "marg_", src: "images/marginalias/Luttrell_coffin_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_doubleheaded_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_doubleheadedguy_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_dragon_nn.png" },
    { id: "marg_", src: "images/marginalias/luttrell_dragoncreature.png" },
    { id: "marg_", src: "images/marginalias/luttrell_dragoneatingguy_nn.png" },
    { id: "marg_", src: "images/marginalias/luttrell_dragonwithbugwings_nn.png" },
    { id: "marg_", src: "images/marginalias/luttrell_fishhorseman_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_fishman_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_fishsquid_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_goofyfishman_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_griffin_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_hoodguy_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_monkeyridingbird_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_monster_n.png" },
    { id: "marg_", src: "images/marginalias/Luttrell_platypuspig_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_psalter_devourer_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_rabbit_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_rodent_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_sadmerman_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_sexydemonboots_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_sheep_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_sillystork_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_snail_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_snail2_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_stripeyguy_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_triangledemon_n.png" },
    { id: "marg_", src: "images/marginalias/luttrell_triangleguy.png" },
    { id: "marg_", src: "images/marginalias/luttrell_tripleheaded_n.png" },
    { id: "marg_", src: "images/marginalias/luttrellcatdirp_n.png" },
    { id: "marg_", src: "images/marginalias/Marginalis (1).png" },
    { id: "marg_", src: "images/marginalias/Marginalis (2).png" },
    { id: "marg_", src: "images/marginalias/Marginalis (3).png" },
    { id: "marg_", src: "images/marginalias/Marginalis.png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (1).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (2).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (3).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (4).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (5).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (6).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (7).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (9).png" },
    { id: "marg_", src: "images/marginalias/Marginalis_ (11).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (3).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (5).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (7).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (10).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (14).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (15).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (16).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (17).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (18).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (19).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (20).png" },
    { id: "marg_", src: "images/marginalias/Marginaliss (21).png" },
    { id: "marg_", src: "images/marginalias/MS_Bodley_cat_n.png" },
    { id: "marg_", src: "images/marginalias/MS_Bodley_cats_n.png" },
    { id: "marg_", src: "images/marginalias/paris_bible_1485_snailcat_n.png" },
    { id: "marg_", src: "images/marginalias/Peterborough_Psalter_and_Bestiary_amphisbaena_n.png" },
    { id: "marg_", src: "images/marginalias/Picsart_25-06-03_04-10-08-701.png" },
    { id: "marg_", src: "images/marginalias/pointingdemon.png" },
    { id: "marg_", src: "images/marginalias/Pontifical_of_Guillaume_Durand_Avignon_before_1390.png" },
    { id: "marg_", src: "images/marginalias/prayer_book_Bruges_1480-1490_cat_organ_n.png" },
    { id: "marg_", src: "images/marginalias/provencebookofhours_M.358_fol. 13r_boarbishop_n.png" },
    { id: "marg_", src: "images/marginalias/rabbit_trump.png" },
    { id: "marg_", src: "images/marginalias/romans_arthuriens_robert_de_boron_heron_n.png" },
    { id: "marg_", src: "images/marginalias/Royal_MS_12c_XIX_cat1_n.png" },
    { id: "marg_", src: "images/marginalias/Royal_MS_12C_XIX_cat2_n.png" },
    { id: "marg_", src: "images/marginalias/rutland_psalter_1260_snail_n.png" },
    { id: "marg_", src: "images/marginalias/rutland_psalter_amphisbaena_m.png" },
    { id: "marg_", src: "images/marginalias/rutland_psalter_birdfluteguy_n.png" },
    { id: "marg_", src: "images/marginalias/Rutland_psalter_birdman_n.png" },
    { id: "marg_", src: "images/marginalias/rutland_psalter_dragon_with_guy_nn.png" },
    { id: "marg_", src: "images/marginalias/rutland_psalter_hydra_n.png" },
    { id: "marg_", src: "images/marginalias/Scheibler_Armorial_1450-1480_cat_n.png" },
    { id: "marg_", src: "images/marginalias/skeleton_luttrell_nn.png" },
    { id: "marg_", src: "images/marginalias/smileycreature_luttrell_n.png" },
    { id: "marg_", src: "images/marginalias/sphinx_1.png" },
    { id: "marg_", src: "images/marginalias/the_book_of_knighthood_1460.png" },
    { id: "marg_", src: "images/marginalias/The_Maastricht_Hours_snailcat_n.png" },
    { id: "marg_", src: "images/marginalias/the_maastricht_hours_snailguy_n.png" },
    { id: "marg_", src: "images/marginalias/The_Ormesby_Psalter_cat_m.png" },
    { id: "marg_", src: "images/marginalias/unknown_source_15th-c_frod.png" },
    { id: "marg_", src: "images/marginalias/Vincent _of_Beauvais_Speculum_historiale_Bruges_1455_n.png" },
    { id: "marg_", src: "images/marginalias/vincent _of_beauvais_speculum_historiale_bruges_1455_reverse.png" },
    { id: "marg_", src: "images/marginalias/Vincent_of_Beauvai_ Speculum_historiale_Bruges_1455_dragon_m.png" },
    { id: "marg_", src: "images/marginalias/Vincent_of_Beauvais_Speculum_historiale_Bruges_ca_1455_demon_m.png" },
    { id: "marg_", src: "images/marginalias/Worksop_bestiary_bat1_n.png" },
    { id: "marg_", src: "images/marginalias/worksop_bestiary_bat2_n.png" },
    { id: "marg_", src: "images/marginalias/worksop_bestiary_multicolouredcats_n.png" },
    { id: "marg_", src: "images/marginalias/worksopbestiary_elephantfigtingdragon_n.png" },
    { id: "marg_", src: "images/marginalias/yates_thompson_ms_29_basilisk_nn.png" }
  ]
};

console.log("✓ Assets cargados desde assets.js:", window.ASSETS);
